// ----------------------------------------------------------
// DO NOT CHANGE THIS FILE MANUALLY.
// This code is automatically generated by the maven build.
// ----------------------------------------------------------


export enum Alignment { /* com.aternity.endusercomm.message.Alignment */
    Left = 'Left',
    Center = 'Center',
    Right = 'Right',
}

export enum ButtonAction { /* com.aternity.endusercomm.message.ButtonAction */
    Cancel = 'Cancel',
    Acknowledge = 'Acknowledge',
}

export enum ButtonStyle { /* com.aternity.endusercomm.message.ButtonStyle */
    Primary = 'Primary',
    Secondary = 'Secondary',
    Plain = 'Plain',
}

export enum MessageStatus { /* com.aternity.endusercomm.message.MessageStatus */
    Triggered = 'Triggered',
    Rendered = 'Rendered',
    Acknowledged = 'Acknowledged',
    Expired = 'Expired',
}

export enum MessageType { /* com.aternity.endusercomm.message.MessageType */
    Notification = 'Notification',
}

export interface MessageButton {// com.aternity.endusercomm.message.MessageButton, depends on classes: com.aternity.endusercomm.message.ButtonAction, com.aternity.endusercomm.message.ButtonStyle
    text: string
    style: ButtonStyle
    action: ButtonAction
}

export interface MessageButtons {// com.aternity.endusercomm.message.MessageButtons, depends on classes: com.aternity.endusercomm.message.Alignment, com.aternity.endusercomm.message.MessageButton
    alignment: Alignment
    buttons: MessageButton[]
}

export interface MessageButtonsText {// com.aternity.endusercomm.message.MessageButtonsText
    buttonText: string[]
}

export interface MessageChannel {// com.aternity.endusercomm.message.MessageChannel
    riverbed: boolean
}

export interface MessageLogo {// com.aternity.endusercomm.message.MessageLogo, depends on classes: com.aternity.endusercomm.message.Alignment
    alignment: Alignment
}

export interface UiBrandingInfo {// com.aternity.endusercomm.management.UiBrandingInfo
    brandingId: string
    brandingName: string
    primaryColor: string
    secondaryColor: string
    backgroundColor: string
    textColor: string
    logo: string
}

export interface UiMessageTemplate {// com.aternity.endusercomm.management.UiMessageTemplate, depends on classes: com.aternity.endusercomm.management.UiBrandingInfo, com.aternity.endusercomm.message.MessageButtons, com.aternity.endusercomm.message.MessageChannel, com.aternity.endusercomm.message.MessageLogo, com.aternity.endusercomm.message.MessageType
    id: string
    name: string
    description: string
    updatedAt: number
    updatedBy: string
    baseTemplateName: string
    type: MessageType
    channels: MessageChannel
    html: string
    css: string
    titleLexical: string
    bodyLexical: string
    branding: UiBrandingInfo
    buttons: MessageButtons
    logo: MessageLogo
}

export interface UiAgentMessageData {// com.aternity.endusercomm.agent.UiAgentMessageData, depends on classes: com.aternity.endusercomm.management.UiMessageTemplate, com.aternity.endusercomm.message.MessageButtonsText
    template: UiMessageTemplate
    titleLexical: string
    bodyLexical: string
    buttonsText: MessageButtonsText
    expirationTime: number
}

export interface UiBaseTemplate {// com.aternity.endusercomm.management.UiBaseTemplate
    name: string
    html: string
    css: string
}

export interface UiEntityGroup {// com.aternity.endusercomm.management.UiEntityGroup
    id: number
    name: string
}

export interface UiMessageDefinition {// com.aternity.endusercomm.management.UiMessageDefinition, depends on classes: com.aternity.endusercomm.message.MessageButtonsText
    definitionId: string
    definitionName: string
    updatedAt: number
    updatedBy: string
    templateId: string
    titleLexical: string
    bodyLexical: string
    buttonsText: MessageButtonsText
}

export interface UiMessageInfo {// com.aternity.endusercomm.management.UiMessageInfo
    definitionId: string
    definitionName: string
    updatedAt: number
    templateId: string
}

export interface UiMessageTemplateInfo {// com.aternity.endusercomm.management.UiMessageTemplateInfo, depends on classes: com.aternity.endusercomm.message.MessageChannel, com.aternity.endusercomm.message.MessageType
    id: string
    name: string
    updatedAt: number
    description: string
    type: MessageType
    channels: MessageChannel
}

export interface UiNewMessageDefinitionRequest {// com.aternity.endusercomm.management.UiNewMessageDefinitionRequest
    name: string
    templateId: string
    titleText: string
    bodyText: string
    buttonText: string
}

export interface UiTriggerMessageForDeviceRequest {// com.aternity.endusercomm.management.UiTriggerMessageForDeviceRequest
    definitionId: string
    expirationTimeSeconds: number
    deviceName: string
}

export interface UiTriggerMessageForEntityGroupRequest {// com.aternity.endusercomm.management.UiTriggerMessageForEntityGroupRequest
    definitionId: string
    expirationTimeSeconds: number
    entityGroup: number
}

export interface UiTriggerResponse {// com.aternity.endusercomm.management.UiTriggerResponse
    triggerId: string
    devicesCount: number
    errorMessage: string
}

export interface UiTriggeredMessage {// com.aternity.endusercomm.agent.UiTriggeredMessage, depends on classes: com.aternity.endusercomm.message.MessageType
    messageType: MessageType
    triggerTargetId: string
    expirationTime: number
    username: string
    renderUrl: string
    popupWindowWidth: number
    popupWindowHeight: number
}

export interface UiTriggeredMessages {// com.aternity.endusercomm.agent.UiTriggeredMessages, depends on classes: com.aternity.endusercomm.agent.UiTriggeredMessage
    pollingFreqSeconds: number
    messages: UiTriggeredMessage[]
}

export interface UiUpdateBrandingRequest {// com.aternity.endusercomm.management.UiUpdateBrandingRequest
    brandingName: string
    primaryColor: string
    secondaryColor: string
    backgroundColor: string
    textColor: string
    logo: string
}

export interface UiUpdateMessageStatus {// com.aternity.endusercomm.agent.UiUpdateMessageStatus, depends on classes: com.aternity.endusercomm.message.MessageStatus
    messageStatus: MessageStatus
}

export interface UiUpdateMessageTemplateRequest {// com.aternity.endusercomm.management.UiUpdateMessageTemplateRequest, depends on classes: com.aternity.endusercomm.message.MessageButtons, com.aternity.endusercomm.message.MessageChannel, com.aternity.endusercomm.message.MessageLogo, com.aternity.endusercomm.message.MessageType
    name: string
    description: string
    type: MessageType
    baseTemplateName: string
    brandingId: string
    titleLexical: string
    bodyLexical: string
    buttons: MessageButtons
    channels: MessageChannel
    logo: MessageLogo
}

export interface UiUserPrivileges {// com.aternity.endusercomm.management.UiUserPrivileges
    view: boolean
    manageBrandConfiguration: boolean
    approveBrandConfiguration: boolean
    manageMessages: boolean
    approveMessages: boolean
    sendMessages: boolean
}
