// ----------------------------------------------------------
// DO NOT CHANGE THIS FILE MANUALLY.
// This code is automatically generated by the maven build.
// ----------------------------------------------------------

import type { AxiosHeaders, AxiosResponse, HeadersDefaults, RawAxiosRequestHeaders } from 'axios'
import axios from 'axios'
import type {
    UiAgentMessageData,
    UiBaseTemplate,
    UiBrandingInfo,
    UiEntityGroup,
    UiMessageDefinition,
    UiMessageInfo,
    UiMessageTemplate,
    UiMessageTemplateInfo,
    UiNewMessageDefinitionRequest,
    UiTriggerMessageForDeviceRequest,
    UiTriggerMessageForEntityGroupRequest,
    UiTriggerResponse,
    UiTriggeredMessages,
    UiUpdateBrandingRequest,
    UiUpdateMessageStatus,
    UiUpdateMessageTemplateRequest,
    UiUserPrivileges,
} from "./be-types"

// Utility function to extract parameter from search or hash
function getParamFromUrl(param: string): string | null {
    if (typeof window === 'undefined') {
        return null
    }
    let parts: string[] = window.location.search.split(param)
    if (parts.length < 2) {
        console.log("Cannot get " + param + " from search, Trying from hash")
        parts = window.location.hash.split(param)
        if (parts.length < 2) {
            console.log("Cannot get " + param + " from hash, return null")
            return null
        }
    }
    const res = parts[1].split('&')[0]
    console.log(param, res)
    return res
}

function getAccountNumberFromUrl(): number {
    const account: string | null = getParamFromUrl('ACCT=')
    if (account === null){
        console.log('No account ID, defaulting to 0')
        return 0
    }
    const acct: number = +account
    console.log('accountId', acct)
    return acct
}

const mockBaseUrl = process.env.NODE_ENV === 'development' && process.env.NEXT_PUBLIC_API_BASE_URL
const apiBaseUrl = mockBaseUrl || (typeof window !== 'undefined' ? window.location.origin : '')

const axiosHeaders: RawAxiosRequestHeaders | AxiosHeaders | Partial<HeadersDefaults> = {
    'Content-Type': 'application/json',
}
const securityToken = getParamFromUrl('SECURITY=')
if (securityToken != null) {
   axiosHeaders.aternity_security = decodeURIComponent(securityToken)
} else {
    console.log('No SECURITY')
}
export const apiClient = axios.create({
    baseURL: apiBaseUrl,
    headers: axiosHeaders,
})

const accountId = getAccountNumberFromUrl()


class UiAgentMessageHttpService {
    async getMessageData(agent_auth: string, triggerTargetId: string): Promise<AxiosResponse<UiAgentMessageData>> {
        return await apiClient.get(`/component/endUserComm/agentApi/message/data/${encodeURIComponent(triggerTargetId)}?agent_auth=${encodeURIComponent(agent_auth)}`)
    }

    async getTriggeredMessages(agent_auth: string): Promise<AxiosResponse<UiTriggeredMessages>> {
        return await apiClient.get(`/component/endUserComm/agentApi/messages?agent_auth=${encodeURIComponent(agent_auth)}`)
    }

    async updateMessageStatus(agent_auth: string, triggerTargetId: string, body: UiUpdateMessageStatus): Promise<AxiosResponse<boolean>> {
        return await apiClient.put(`/component/endUserComm/agentApi/message/${encodeURIComponent(triggerTargetId)}?agent_auth=${encodeURIComponent(agent_auth)}`, body)
    }

}

class UiMgmtGroupsHttpService {
    async getEntityGroups(): Promise<AxiosResponse<UiEntityGroup[]>> {
        return await apiClient.get(`/component/endUserComm/api/mgmt/entityGroups?ACCT=${accountId}`)
    }

}

class UiMgmtMessageHttpService {
    async createMsgDefinition(body: UiNewMessageDefinitionRequest): Promise<AxiosResponse<UiMessageDefinition>> {
        return await apiClient.post(`/component/endUserComm/api/mgmt/message?ACCT=${accountId}`, body)
    }

    async createTemplate(body: UiUpdateMessageTemplateRequest): Promise<AxiosResponse<UiMessageTemplate>> {
        return await apiClient.post(`/component/endUserComm/api/mgmt/message/template?ACCT=${accountId}`, body)
    }

    async deleteMsgDefinition(definitionId: string): Promise<AxiosResponse<UiMessageInfo[]>> {
        return await apiClient.delete(`/component/endUserComm/api/mgmt/message/${encodeURIComponent(definitionId)}?ACCT=${accountId}`)
    }

    async getBaseTemplate(baseTemplateName: string): Promise<AxiosResponse<UiBaseTemplate>> {
        return await apiClient.get(`/component/endUserComm/api/mgmt/message/template/baseTemplate/${encodeURIComponent(baseTemplateName)}?ACCT=${accountId}`)
    }

    async getBaseTemplates(): Promise<AxiosResponse<string[]>> {
        return await apiClient.get(`/component/endUserComm/api/mgmt/message/template/baseTemplate?ACCT=${accountId}`)
    }

    async getBranding(brandingId: string): Promise<AxiosResponse<UiBrandingInfo>> {
        return await apiClient.get(`/component/endUserComm/api/mgmt/message/branding/${encodeURIComponent(brandingId)}?ACCT=${accountId}`)
    }

    async getDefaultBranding(): Promise<AxiosResponse<UiBrandingInfo>> {
        return await apiClient.get(`/component/endUserComm/api/mgmt/message/branding/default?ACCT=${accountId}`)
    }

    async getMsgDefinition(definitionId: string): Promise<AxiosResponse<UiMessageDefinition>> {
        return await apiClient.get(`/component/endUserComm/api/mgmt/message/${encodeURIComponent(definitionId)}?ACCT=${accountId}`)
    }

    async getMsgDefinitions(): Promise<AxiosResponse<UiMessageInfo[]>> {
        return await apiClient.get(`/component/endUserComm/api/mgmt/message?ACCT=${accountId}`)
    }

    async getTemplate(templateId: string): Promise<AxiosResponse<UiMessageTemplate>> {
        return await apiClient.get(`/component/endUserComm/api/mgmt/message/template/${encodeURIComponent(templateId)}?ACCT=${accountId}`)
    }

    async getTemplates(): Promise<AxiosResponse<UiMessageTemplateInfo[]>> {
        return await apiClient.get(`/component/endUserComm/api/mgmt/message/template?ACCT=${accountId}`)
    }

    async triggerMsgForDevice(body: UiTriggerMessageForDeviceRequest): Promise<AxiosResponse<UiTriggerResponse>> {
        return await apiClient.post(`/component/endUserComm/api/mgmt/message/trigger/device?ACCT=${accountId}`, body)
    }

    async triggerMsgForGroup(body: UiTriggerMessageForEntityGroupRequest): Promise<AxiosResponse<UiTriggerResponse>> {
        return await apiClient.post(`/component/endUserComm/api/mgmt/message/trigger/entityGroup?ACCT=${accountId}`, body)
    }

    async updateBranding(brandingId: string, body: UiUpdateBrandingRequest): Promise<AxiosResponse<UiBrandingInfo>> {
        return await apiClient.put(`/component/endUserComm/api/mgmt/message/branding/${encodeURIComponent(brandingId)}?ACCT=${accountId}`, body)
    }

    async updateMsgDefinition(definitionId: string, body: UiNewMessageDefinitionRequest): Promise<AxiosResponse<UiMessageDefinition>> {
        return await apiClient.put(`/component/endUserComm/api/mgmt/message/${encodeURIComponent(definitionId)}?ACCT=${accountId}`, body)
    }

    async updateTemplate(templateId: string, body: UiUpdateMessageTemplateRequest): Promise<AxiosResponse<UiMessageTemplate>> {
        return await apiClient.put(`/component/endUserComm/api/mgmt/message/template/${encodeURIComponent(templateId)}?ACCT=${accountId}`, body)
    }

}

class UiMgmtSearchHttpService {
    async searchDevices(hostnameStartsWith: string): Promise<AxiosResponse<string[]>> {
        return await apiClient.get(`/component/endUserComm/api/mgmt/devices/search?ACCT=${accountId}&hostnameStartsWith=${encodeURIComponent(hostnameStartsWith)}`)
    }

}

class UiMgmtUserHttpService {
    async getUserPrivileges(): Promise<AxiosResponse<UiUserPrivileges>> {
        return await apiClient.get(`/component/endUserComm/api/mgmt/user/privileges?ACCT=${accountId}`)
    }

}

export class EndUserCommSdk {
    readonly uiAgentMessage: UiAgentMessageHttpService = new UiAgentMessageHttpService()
    readonly uiMgmtGroups: UiMgmtGroupsHttpService = new UiMgmtGroupsHttpService()
    readonly uiMgmtMessage: UiMgmtMessageHttpService = new UiMgmtMessageHttpService()
    readonly uiMgmtSearch: UiMgmtSearchHttpService = new UiMgmtSearchHttpService()
    readonly uiMgmtUser: UiMgmtUserHttpService = new UiMgmtUserHttpService()
}

export const endUserCommSdk: EndUserCommSdk = new EndUserCommSdk()
