/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    templates: Template;
    branding: Branding;
    policies: Policy;
    variables: Variable;
    buttons: Button;
    messages: Message;
    divisions: Division;
    'user-groups': UserGroup;
    'delivery-rules': DeliveryRule;
    'message-analytics': MessageAnalytic;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    templates: TemplatesSelect<false> | TemplatesSelect<true>;
    branding: BrandingSelect<false> | BrandingSelect<true>;
    policies: PoliciesSelect<false> | PoliciesSelect<true>;
    variables: VariablesSelect<false> | VariablesSelect<true>;
    buttons: ButtonsSelect<false> | ButtonsSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    divisions: DivisionsSelect<false> | DivisionsSelect<true>;
    'user-groups': UserGroupsSelect<false> | UserGroupsSelect<true>;
    'delivery-rules': DeliveryRulesSelect<false> | DeliveryRulesSelect<true>;
    'message-analytics': MessageAnalyticsSelect<false> | MessageAnalyticsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates".
 */
export interface Template {
  id: string;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  description?: string | null;
  messageType: 'notification';
  /**
   * Number of messages using this template
   */
  usage?: number | null;
  branding?: (string | null) | Branding;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branding".
 */
export interface Branding {
  id: string;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  primaryColor?: string | null;
  secondaryColor?: string | null;
  logo: string | Media;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policies".
 */
export interface Policy {
  id: string;
  name: string;
  type: 'fatigue' | 'sequencing' | 'vip' | 'quietHours' | 'routing' | 'dndExceptions';
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  fatigue?: {
    maxSurveysPerWeek: number;
    minDaysBetweenSurveys: number;
  };
  sequencing?: {
    allowParallelExecution?: boolean | null;
    maxConcurrentActions?: number | null;
    queueNonIntrusiveMessages?: boolean | null;
  };
  vip?: {
    reminderFrequency?: ('more_frequent' | 'less_frequent' | 'custom') | null;
    customIntervalDays?: number | null;
  };
  quietHours?: {
    timezone: string;
    windows?:
      | {
          /**
           * e.g., 22:00
           */
          start: string;
          /**
           * e.g., 07:00
           */
          end: string;
          /**
           * e.g., Mon-Fri
           */
          days?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Optional list of VIP user IDs exempt from quiet hours.
     */
    vipUserIds?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  routing?: {
    preferredChannel: 'device' | 'teams' | 'both';
    /**
     * Used when preferredChannel = both
     */
    bothStrategy?: ('parallel' | 'fallbackToTeams' | 'fallbackToDevice') | null;
  };
  dndExceptions?: {
    /**
     * E.g., { "kinds": ["urgent", "security"] }
     */
    allowedDuringDndKinds?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variables".
 */
export interface Variable {
  id: string;
  key: string;
  label: string;
  type: 'string' | 'number' | 'boolean' | 'date' | 'dateTime' | 'url' | 'email' | 'enum';
  enumOptions?:
    | {
        value: string;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  required?: boolean | null;
  description?: string | null;
  /**
   * e.g., date: YYYY-MM-DD or number: 0.00
   */
  formatHint?: string | null;
  /**
   * Optional example value for previews/tests
   */
  sampleValue?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "buttons".
 */
export interface Button {
  id: string;
  name: string;
  label?: string | null;
  icon?: string | null;
  otherAttributes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: string;
  name: string;
  description?: string | null;
  messageType: 'notification';
  template?: (string | null) | Template;
  targetGroup: string | UserGroup;
  /**
   * Expiration date for the message
   */
  expiredIn?: string | null;
  deliveryRules?: (string | DeliveryRule)[] | null;
  deliveryMode?: ('intrusive' | 'non-intrusive') | null;
  status?: ('draft' | 'active' | 'scheduled' | 'completed') | null;
  priority?: ('normal' | 'high' | 'urgent') | null;
  deliverySchedule?: ('immediate' | 'scheduled') | null;
  scheduledDate?: string | null;
  /**
   * Calculated response rate percentage
   */
  responseRate?: number | null;
  totalRecipients?: number | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-groups".
 */
export interface UserGroup {
  id: string;
  name: string;
  description?: string | null;
  /**
   * Dynamic criteria for user selection
   */
  criteria?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  estimatedSize?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "delivery-rules".
 */
export interface DeliveryRule {
  id: string;
  name: string;
  ruleType: 'fatigue' | 'sequencing' | 'vip' | 'urgency';
  isEnabled?: boolean | null;
  /**
   * Rule-specific settings
   */
  configuration?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  targetUserRole?: ('vip' | 'it-staff' | 'general' | 'all') | null;
  /**
   * Optional target user group for this rule
   */
  targetGroup?: (string | null) | UserGroup;
  /**
   * Rule priority for conflict resolution
   */
  priority?: number | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "divisions".
 */
export interface Division {
  id: string;
  name: string;
  code: string;
  description?: string | null;
  parentDivision?: (string | null) | Division;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "message-analytics".
 */
export interface MessageAnalytic {
  id: string;
  message: string | Message;
  totalSent?: number | null;
  totalViewed?: number | null;
  totalResponded?: number | null;
  /**
   * Calculated response rate
   */
  responseRate?: number | null;
  deliveryDate?: string | null;
  /**
   * Stats per channel
   */
  channelBreakdown?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  userInteractions?:
    | {
        userId?: string | null;
        action?: string | null;
        timestamp?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'templates';
        value: string | Template;
      } | null)
    | ({
        relationTo: 'branding';
        value: string | Branding;
      } | null)
    | ({
        relationTo: 'policies';
        value: string | Policy;
      } | null)
    | ({
        relationTo: 'variables';
        value: string | Variable;
      } | null)
    | ({
        relationTo: 'buttons';
        value: string | Button;
      } | null)
    | ({
        relationTo: 'messages';
        value: string | Message;
      } | null)
    | ({
        relationTo: 'divisions';
        value: string | Division;
      } | null)
    | ({
        relationTo: 'user-groups';
        value: string | UserGroup;
      } | null)
    | ({
        relationTo: 'delivery-rules';
        value: string | DeliveryRule;
      } | null)
    | ({
        relationTo: 'message-analytics';
        value: string | MessageAnalytic;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates_select".
 */
export interface TemplatesSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  messageType?: T;
  usage?: T;
  branding?: T;
  body?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branding_select".
 */
export interface BrandingSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  primaryColor?: T;
  secondaryColor?: T;
  logo?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policies_select".
 */
export interface PoliciesSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  generateSlug?: T;
  slug?: T;
  fatigue?:
    | T
    | {
        maxSurveysPerWeek?: T;
        minDaysBetweenSurveys?: T;
      };
  sequencing?:
    | T
    | {
        allowParallelExecution?: T;
        maxConcurrentActions?: T;
        queueNonIntrusiveMessages?: T;
      };
  vip?:
    | T
    | {
        reminderFrequency?: T;
        customIntervalDays?: T;
      };
  quietHours?:
    | T
    | {
        timezone?: T;
        windows?:
          | T
          | {
              start?: T;
              end?: T;
              days?: T;
              id?: T;
            };
        vipUserIds?: T;
      };
  routing?:
    | T
    | {
        preferredChannel?: T;
        bothStrategy?: T;
      };
  dndExceptions?:
    | T
    | {
        allowedDuringDndKinds?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variables_select".
 */
export interface VariablesSelect<T extends boolean = true> {
  key?: T;
  label?: T;
  type?: T;
  enumOptions?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  required?: T;
  description?: T;
  formatHint?: T;
  sampleValue?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "buttons_select".
 */
export interface ButtonsSelect<T extends boolean = true> {
  name?: T;
  label?: T;
  icon?: T;
  otherAttributes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  messageType?: T;
  template?: T;
  targetGroup?: T;
  expiredIn?: T;
  deliveryRules?: T;
  deliveryMode?: T;
  status?: T;
  priority?: T;
  deliverySchedule?: T;
  scheduledDate?: T;
  responseRate?: T;
  totalRecipients?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "divisions_select".
 */
export interface DivisionsSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  description?: T;
  parentDivision?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-groups_select".
 */
export interface UserGroupsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  criteria?: T;
  estimatedSize?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "delivery-rules_select".
 */
export interface DeliveryRulesSelect<T extends boolean = true> {
  name?: T;
  ruleType?: T;
  isEnabled?: T;
  configuration?: T;
  targetUserRole?: T;
  targetGroup?: T;
  priority?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "message-analytics_select".
 */
export interface MessageAnalyticsSelect<T extends boolean = true> {
  message?: T;
  totalSent?: T;
  totalViewed?: T;
  totalResponded?: T;
  responseRate?: T;
  deliveryDate?: T;
  channelBreakdown?: T;
  userInteractions?:
    | T
    | {
        userId?: T;
        action?: T;
        timestamp?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}