/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    templates: Template;
    'branding-packages': BrandingPackage;
    policies: Policy;
    variables: Variable;
    channels: Channel;
    buttons: Button;
    messages: Message;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    templates: TemplatesSelect<false> | TemplatesSelect<true>;
    'branding-packages': BrandingPackagesSelect<false> | BrandingPackagesSelect<true>;
    policies: PoliciesSelect<false> | PoliciesSelect<true>;
    variables: VariablesSelect<false> | VariablesSelect<true>;
    channels: ChannelsSelect<false> | ChannelsSelect<true>;
    buttons: ButtonsSelect<false> | ButtonsSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates".
 */
export interface Template {
  id: number;
  name: string;
  type: 'survey' | 'confirmation' | 'notification' | 'reminder' | 'self-service';
  division?: ('Corporate' | 'IT Operations' | 'Engineering' | 'Support' | 'Sales' | 'Finance' | 'Marketing') | null;
  category?: ('pre-defined' | 'system' | 'custom') | null;
  priority?: ('low' | 'medium' | 'high' | 'urgent') | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  brandingRef?: (number | null) | BrandingPackage;
  policyRefs?: (number | Policy)[] | null;
  channelRefs?: (number | Channel)[] | null;
  buttonRefs?: (number | Button)[] | null;
  /**
   * Number of active campaigns using this template
   */
  usageCount?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branding-packages".
 */
export interface BrandingPackage {
  id: number;
  name: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  themeDesigner?: {
    primaryColor?: string | null;
    secondaryColor?: string | null;
    backgroundColor?: string | null;
    textColor?: string | null;
    scope?:
      | (
          | 'all'
          | 'survey'
          | 'confirmation'
          | 'notification'
          | 'reminder'
          | 'self-service'
          | 'urgent'
          | 'corporate'
          | 'it-operations'
          | 'engineering'
          | 'support'
          | 'sales'
          | 'finance'
          | 'marketing'
        )
      | null;
    logo?: (number | null) | Media;
    /**
     * Logo position relative to title
     */
    logoPos?: ('left-inline' | 'right-inline' | 'before' | 'after' | 'center') | null;
  };
  generalStyling?: {
    /**
     * Text direction
     */
    direction?: ('ltr' | 'rtl') | null;
    /**
     * Message width in pixels
     */
    messageWidth?: number | null;
    /**
     * Title alignment
     */
    titleAlign?: ('left' | 'center' | 'right') | null;
  };
  signature?: {
    text?: string | null;
    position?: ('left' | 'right' | 'center') | null;
  };
  /**
   * Assets used as part of the theme, such as custom icons for buttons, background images, or specialized fonts.
   */
  assets?: (number | Media)[] | null;
  /**
   * Design tokens exported from your theme generator (colors, spacing, radii, typography, semantic states, light/dark variants).
   */
  themeTokens?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Optional allowlist of CSS tokens/styles permitted for branding to prevent arbitrary or unsafe CSS injection.
   */
  cssAllowlist?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policies".
 */
export interface Policy {
  id: number;
  name: string;
  type: 'fatigue' | 'sequencing' | 'vip' | 'quietHours' | 'routing' | 'dndExceptions';
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  fatigue?: {
    maxSurveysPerWeek: number;
    minDaysBetweenSurveys: number;
  };
  sequencing?: {
    allowParallelExecution?: boolean | null;
    maxConcurrentActions?: number | null;
    queueNonIntrusiveMessages?: boolean | null;
  };
  vip?: {
    reminderFrequency?: ('more_frequent' | 'less_frequent' | 'custom') | null;
    customIntervalDays?: number | null;
  };
  quietHours?: {
    timezone: string;
    windows?:
      | {
          /**
           * e.g., 22:00
           */
          start: string;
          /**
           * e.g., 07:00
           */
          end: string;
          /**
           * e.g., Mon-Fri
           */
          days?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Optional list of VIP user IDs exempt from quiet hours.
     */
    vipUserIds?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  routing?: {
    preferredChannel: 'device' | 'teams' | 'both';
    /**
     * Used when preferredChannel = both
     */
    bothStrategy?: ('parallel' | 'fallbackToTeams' | 'fallbackToDevice') | null;
  };
  dndExceptions?: {
    /**
     * E.g., { "kinds": ["urgent", "security"] }
     */
    allowedDuringDndKinds?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "channels".
 */
export interface Channel {
  id: number;
  name: string;
  status: 'configured' | 'disabled';
  description?: string | null;
  supportedMessageTypes?: ('survey' | 'confirmation' | 'notification' | 'reminder' | 'self-service')[] | null;
  capabilities?: ('server-side' | 'oauth')[] | null;
  /**
   * Channel-specific configuration (API keys, endpoints, etc.)
   */
  configuration?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "buttons".
 */
export interface Button {
  id: number;
  name: string;
  label?: string | null;
  icon?: string | null;
  otherAttributes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variables".
 */
export interface Variable {
  id: number;
  key: string;
  label: string;
  type: 'string' | 'number' | 'boolean' | 'date' | 'dateTime' | 'url' | 'email' | 'enum';
  enumOptions?:
    | {
        value: string;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  required?: boolean | null;
  description?: string | null;
  /**
   * e.g., date: YYYY-MM-DD or number: 0.00
   */
  formatHint?: string | null;
  /**
   * Optional example value for previews/tests
   */
  sampleValue?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: number;
  name: string;
  type: 'survey' | 'confirmation' | 'notification' | 'reminder' | 'self-service';
  channel: number | Channel;
  mode: 'intrusive' | 'non-intrusive';
  status: 'active' | 'draft' | 'scheduled' | 'completed';
  priority: 'low' | 'medium' | 'high' | 'urgent';
  responseRate?: {
    /**
     * Response rate percentage
     */
    percentage?: number | null;
    /**
     * Number of responses
     */
    count?: number | null;
    /**
     * Total targeted users
     */
    total?: number | null;
  };
  template: number | Template;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'templates';
        value: number | Template;
      } | null)
    | ({
        relationTo: 'branding-packages';
        value: number | BrandingPackage;
      } | null)
    | ({
        relationTo: 'policies';
        value: number | Policy;
      } | null)
    | ({
        relationTo: 'variables';
        value: number | Variable;
      } | null)
    | ({
        relationTo: 'channels';
        value: number | Channel;
      } | null)
    | ({
        relationTo: 'buttons';
        value: number | Button;
      } | null)
    | ({
        relationTo: 'messages';
        value: number | Message;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates_select".
 */
export interface TemplatesSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  division?: T;
  category?: T;
  priority?: T;
  generateSlug?: T;
  slug?: T;
  body?: T;
  brandingRef?: T;
  policyRefs?: T;
  channelRefs?: T;
  buttonRefs?: T;
  usageCount?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "branding-packages_select".
 */
export interface BrandingPackagesSelect<T extends boolean = true> {
  name?: T;
  generateSlug?: T;
  slug?: T;
  themeDesigner?:
    | T
    | {
        primaryColor?: T;
        secondaryColor?: T;
        backgroundColor?: T;
        textColor?: T;
        scope?: T;
        logo?: T;
        logoPos?: T;
      };
  generalStyling?:
    | T
    | {
        direction?: T;
        messageWidth?: T;
        titleAlign?: T;
      };
  signature?:
    | T
    | {
        text?: T;
        position?: T;
      };
  assets?: T;
  themeTokens?: T;
  cssAllowlist?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policies_select".
 */
export interface PoliciesSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  generateSlug?: T;
  slug?: T;
  fatigue?:
    | T
    | {
        maxSurveysPerWeek?: T;
        minDaysBetweenSurveys?: T;
      };
  sequencing?:
    | T
    | {
        allowParallelExecution?: T;
        maxConcurrentActions?: T;
        queueNonIntrusiveMessages?: T;
      };
  vip?:
    | T
    | {
        reminderFrequency?: T;
        customIntervalDays?: T;
      };
  quietHours?:
    | T
    | {
        timezone?: T;
        windows?:
          | T
          | {
              start?: T;
              end?: T;
              days?: T;
              id?: T;
            };
        vipUserIds?: T;
      };
  routing?:
    | T
    | {
        preferredChannel?: T;
        bothStrategy?: T;
      };
  dndExceptions?:
    | T
    | {
        allowedDuringDndKinds?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variables_select".
 */
export interface VariablesSelect<T extends boolean = true> {
  key?: T;
  label?: T;
  type?: T;
  enumOptions?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  required?: T;
  description?: T;
  formatHint?: T;
  sampleValue?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "channels_select".
 */
export interface ChannelsSelect<T extends boolean = true> {
  name?: T;
  status?: T;
  description?: T;
  supportedMessageTypes?: T;
  capabilities?: T;
  configuration?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "buttons_select".
 */
export interface ButtonsSelect<T extends boolean = true> {
  name?: T;
  label?: T;
  icon?: T;
  otherAttributes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  channel?: T;
  mode?: T;
  status?: T;
  priority?: T;
  responseRate?:
    | T
    | {
        percentage?: T;
        count?: T;
        total?: T;
      };
  template?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}